### ISSUE TITLE
Not recording audio

### ISSUE THREAD

**Issue by dazzzed** [Flam3rboy/puppeteer-stream#1]
I'm trying to record video and audio using puppeteer stream, but it's getting written only the video to the output file:

```
async function videoRecorder() {
  require("puppeteer-stream");
  const puppeteer = require("puppeteer");
  const fs = require("fs");

  const filename = `./recordings/test.mp4`;

  const file = fs.createWriteStream(filename);

  const browser = await puppeteer.launch({
    executablePath:
      "/Applications/Google Chrome.app/Contents/MacOS/Google Chrome",
    headless: true,
    defaultViewport: null,
    devtools: false,
    args: [
      "--window-size=1920,1080",
      "--window-position=1921,0",
      "--autoplay-policy=no-user-gesture-required",
    ],
    ignoreDefaultArgs: ["--mute-audio"],
  });

  const page = await browser.newPage();

  await page.goto(pathToPageWithVideo, {
    waitUntil: "load",
  });

  const stream = await page.getStream({
    audio: true,
    video: true,
  });

  stream.pipe(file);

  setTimeout(async () => {
    await stream.destroy();
    file.close();
    console.log("finished");
  }, 10000);
}
```

**Comment by Flam3rboy** [comment]
i'll have a look tomorrow

**Comment by Flam3rboy** [comment]
You are writing to a ``.mp4``file however the default format is webm.
Also can you send the ``pathToPageWithVideo`` value

**Comment by tiagocostafdm** [comment]
@Flam3rboy I've tried with webm and din't work either.
The `pathToPageWithVideo`  I was testing with was https://www.rtp.pt/play/p8157/e518677/telejornal

**Comment by Flam3rboy** [comment]
also note that chrome doesn't support ``video/mp4``.
Have a look at the [HTML5 MediaRecorder Options](https://developer.mozilla.org/en-US/docs/Web/API/MediaRecorder/MediaRecorder)

**Comment by Flam3rboy** [comment]
weirdly enough everything works without any mimeType options and saving it as an .webm file

**Comment by tiagocostafdm** [comment]
so you got it to save a file with audio and video by setting the mimeType to `video/webm` and saving as webm?

**Comment by Flam3rboy** [comment]
yes everything the same

**Comment by dazzzed** [comment]
@Flam3rboy yes I got it just opened it with another player, thanks.
One more thing, how can I save it as mp3 audio only?

**Comment by Flam3rboy** [comment]
only if the browser supports mp3 just specify the mimeType

**Comment by Aayush-jain007** [comment]
Is there anyway to stream it instead of downloading the video? I want to get a Media Stream of the Browser Tab
