### ISSUE TITLE
[Bug] Page undefined error occurs sometimes

### ISSUE THREAD

**Issue by amsdak15** [Flam3rboy/puppeteer-stream#13]
Hello, thank you for your work!

I've been using puppeteer-stream for over a month now and it works perfectly.

However, sometimes it gives the following error at the starting of the code.

(node:20) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'page' of undefined at /app/node_modules/puppeteer-stream/dist/PuppeteerStream.js:79:63 at Generator.next (<anonymous>) at fulfilled (/app/node_modules/puppeteer-stream/dist/PuppeteerStream.js:5:58) at processTicksAndRejections (internal/process/task_queues.js:95:5)

What can be the reason for this error? And why does it come only once in almost 100 tries? Please let me know how to deal with kind of error?

I believe the error comes because the browser has not started properly.

Thanks again!

PS:
The code where the error comes.
`const browser = await launch({
        defaultViewport: null,
        headless: true,
        args: [
          "--autoplay-policy=no-user-gesture-required",
          '--start-fullscreen',
          '--no-sandbox',
        ],
});
const page = await browser.newPage();
await page.setViewport({ width: 1400, height: 800}); 
const navigationPromise = page.waitForNavigation();`

**Comment by Flam3rboy** [comment]
It says that if it can’t find the extension page, a workaround might be to wait a bit after starting and then get the page

**Comment by amsdak15** [comment]
Thank you for your immediate response.

So, adding `await new Promise(resolve => setTimeout(resolve, 5000));` after defining browser should be okay,right?

**Comment by Flam3rboy** [comment]
I think i need to add it inside the launch option

**Comment by amsdak15** [comment]
Aah okay, thank you very much!

**Comment by amazing-tomotoshi** [comment]
Hello, thank you for your work!
I'm amsdak15's colleague.
Did you fix this bug?
It still occurred sometimes.

**Comment by Flam3rboy** [comment]
It should be fixed now, the lib now ``waitForTarget``.
Also I would advise you to only start the browser once and if you need multiple streams open multiple tabs.
```
npm i puppeteer-stream@2.0.6
```

**Comment by amazing-tomotoshi** [comment]
Thank you very much!
Did you release v2.0.6?
<img width="293" alt="スクリーンショット 2021-07-25 22 43 42" src="https://user-images.githubusercontent.com/67425518/126901353-dab0e413-2e7f-49e3-bac3-dfc1e664c2fc.png">
it seems that it is still v2.0.5

**Comment by Flam3rboy** [comment]
oh yeah I published it to npm but forgot to push it to github

**Comment by amazing-tomotoshi** [comment]
Aah okay, thank you very much!

**Comment by amazing-tomotoshi** [comment]
this error occurred.
`(node:21) UnhandledPromiseRejectionWarning: Error: Failed to launch the browser process!`

this is our code.
`    const browser = await launch({
        // userDataDir: "./Default_3",
        defaultViewport: null,
        headless: true,
        //ignoreDefaultArgs: "--mute-audio",
        args: [
          "--autoplay-policy=no-user-gesture-required",
          '--start-fullscreen',
          '--no-sandbox',
        ],
    });`

What can be the reason for this error?

**Comment by Flam3rboy** [comment]
https://stackoverflow.com/questions/59979188/error-failed-to-launch-the-browser-process-puppeteer
