### ISSUE TITLE
TypeError: page.getStream is not a function

### ISSUE THREAD

**Issue by erikKeresztes** [Flam3rboy/puppeteer-stream#2]
This is my code:
```js
require('puppeteer-stream')
const puppeteer = require('puppeteer')
const fs = require('fs')

const file = fs.createWriteStream('test.webm');

(async () => {
	const browser = await puppeteer.launch();
	const page = await browser.newPage();
	await page.goto('https://example.com');
	const stream = await page.getStream({ audio: true, video: true })
	stream.pipe(file)
})()
```
Though even with the example code it gives the same error for me

**Comment by Flam3rboy** [comment]
ok this is weird, i'll have a look later

**Comment by Flam3rboy** [comment]
Are you sure you've everything the same as the example code?
Can you send me a screenshot/video of you starting the program?

**Comment by Johtax** [comment]
Hello, same issue here. Yesterday was working perfectly.
It seems that it doesn't install the video capture extension. Screenshots:

Before:
![chrome_before](https://user-images.githubusercontent.com/30960434/107242909-c6b83b80-6a2c-11eb-8b30-271b2bddcf88.png)

After:
![chrome_after](https://user-images.githubusercontent.com/30960434/107242960-d768b180-6a2c-11eb-8561-652000779cc1.png)

**Comment by erikKeresztes** [comment]
Weird, I installed it again and it works fine now. No idea why it didn't work before.

**Comment by javimey** [comment]
Hi,

In my case I am having the same issue using the example code.

` UnhandledPromiseRejectionWarning: TypeError: page.getStream is not a function`

I am using node v14.15.0 and I just did a fresh install and getting the same error:

```
{
  "dependencies": {
    "puppeteer": "^7.0.4",
    "puppeteer-stream": "^1.0.7"
  }
}
```

**Comment by erikKeresztes** [comment]
@javimey try installing puppeteer-stream without puppeteer

**Comment by Flam3rboy** [comment]
I think its a problem, because I'm patching the method. I would be better if I create my own launch & getStream method and not adding it to the puppeteer class.

**Comment by erikKeresztes** [comment]
@Flam3rboy you could do something like what ghost-cursor does: https://github.com/Xetera/ghost-cursor

**Comment by Flam3rboy** [comment]
I've now updated the package to use functions instead of patching the methods
