### ISSUE TITLE
[question] Does this support video alpha channel?

### ISSUE THREAD

**Issue by ariel-frischer** [Flam3rboy/puppeteer-stream#25]
Does this support a video alpha channel? I've noticed webm does support alpha background channel, and so does .mov but I'm not sure if this library enables it.

**Comment by Flam3rboy** [comment]
You would need to convert it using [ffmpeg](#9) because chrome only allows to record using [webm](https://github.com/Flam3rboy/puppeteer-stream/issues/19#issuecomment-937537304).

**Comment by evelynhathaway** [comment]
`MediaRecorder` in Chrome supports alpha in webm videos now, but currently that's only usable in `canvas.captureStream()` as far as I can tell. See [fixed Chromium bug](https://issues.chromium.org/issues/40505947).

There isn't alpha support for any method to record non-canvas element
- `chrome.tabCapture.capture()` (Chrome extension API used by this project) does not appear to output alpha in v130 stable
- `Page.startScreencast()` (Chrome DevTools protocol) was reported to also add a background in https://github.com/ChromeDevTools/devtools-protocol/issues/162),
- `navigator.mediaDevices.getDisplayMedia()` (native API)

If anyone runs across this needing alpha, it may be worth compositing in the browser, chromakeying, creating a video in ffmpeg from a stream of PNG captures, or using native window capture of a transparent electron app instead.
