### ISSUE TITLE
outdated puppeteer version

### ISSUE THREAD

**Issue by KennyHarrer** [Flam3rboy/puppeteer-stream#26]
ERROR: https://www.toptal.com/developers/hastebin/umowehuwej.sql
not sure what else I can say... All I do is start a steam with:

`const stream = await getStream(tab, { audio: true, video: true, frameSize: 1000 })`

launch options:

`            browser = await launch({
                headless: false,
                args: ['--window-size=1080,1920', '--start-fullscreen', '--autoplay-policy=no-user-gesture-required', '--disable-infobars', "--no-default-browser-check","–allow-file-access-from-files","-disable-web-security"],
                ignoreDefaultArgs: ['--enable-automation'],
            });`

**Comment by KennyHarrer** [comment]
updated error link: https://pastebin.com/raw/LF4pfdxA

**Comment by KennyHarrer** [comment]
after adding in a missing await now im getting this error: https://pastebin.com/raw/XTwaFXng

**Comment by Flam3rboy** [comment]
It looks like ``chrome.tabCapture`` isn't defined. What version of puppeteer are you using?

**Comment by KennyHarrer** [comment]
![image](https://user-images.githubusercontent.com/71682824/150006633-216caafb-8754-4d71-b2a1-6b7a0098cc22.png)

**Comment by Flam3rboy** [comment]
It looks like you are using an outdated version of puppeteer, please upgrade to the latest one:
```
npm install puppeteer@latest
```

**Comment by KennyHarrer** [comment]
I did not update, however after I removed 2 flags from the launch args it started working. I currently cannot get to my computer to check which two resolved this issue, but I will let you know as soon as I find them.

**Comment by Flam3rboy** [comment]
@KennyHarrer any updates?

**Comment by KennyHarrer** [comment]
Completely forgot about this, Ill try to get an answer to you by tonight.
