### ISSUE TITLE
Screencast at 60fps

### ISSUE THREAD

**Issue by html5maker** [Flam3rboy/puppeteer-stream#27]
Is it possible to use puppeteer-stream to record a screencast at 60fps?

**Comment by Flam3rboy** [comment]
Sadly this is not possible with the [chrome tab capture](https://developer.chrome.com/docs/extensions/reference/tabCapture/) + [HTML5 Media Recorder](https://developer.mozilla.org/en-US/docs/Web/API/MediaRecorder) api
