### ISSUE TITLE
Version 2.0.7 on npm missing extension fix

### ISSUE THREAD

**Issue by TalkLounge** [Flam3rboy/puppeteer-stream#28]
Version 2.0.7 on [npm](https://www.npmjs.com/package/puppeteer-stream) is missing the [extension fix](https://github.com/Flam3rboy/puppeteer-stream/pull/11)
Version 2.0.5 on npm has the fix, on version 2.0.6 on npm I haven't tested it

**Comment by Flam3rboy** [comment]
I can't reproduce it: I've downloaded the latest npm package and inspected it
and the extension fix is still in it:
![image](https://user-images.githubusercontent.com/34555296/145640736-f520700d-00f7-4bbf-89e0-2a5bd527fcab.png)
