### ISSUE TITLE
Can you fix the background.js? (Screen resolution problem)

### ISSUE THREAD

**Issue by wesias7** [Flam3rboy/puppeteer-stream#30]
```js
function START_RECORDING({ index, video, audio, frameSize, audioBitsPerSecond, videoBitsPerSecond, bitsPerSecond, mimeType, videoConstraints }) {
	chrome.tabCapture.capture(
		{
			audio,
			video,
			videoConstraints: videoConstraints || {}
		},
```

then,

```js
const videoConstraints = { mandatory: { minWidth: 480, minHeight: 680, maxWidth: 480, maxHeight: 680 } }
const stream = await puppeteerStream.getStream(page, { audio: true, video: true, videoConstraints })
console.log("recording")

videoConstraints: {
      mandatory: {
          minWidth: 1920,
          minHeight: 1080,
          maxWidth: 1920,
          maxHeight: 1080
      }
  }
```

If you let me put the video constant value in, the problem will be solved. Make sure to write down the size you want.
- Solving the problem that's being recorded throughout the PC screen.
- Small windows can be recorded.

Nice program. I'll use it well.

**Comment by natashafenech** [comment]
I can confirm this works, any plans for this to get fixed?

**Comment by wesias7** [comment]
@natashafenech If reflected, even a small screen can be recorded. I'm using it.

**Comment by cdemi** [comment]
@Flam3rboy shall we attempt to make a Pull Request for this fix?

**Comment by Flam3rboy** [comment]
Yes, I would love to merge it 👍

**Comment by natashafenech** [comment]
Perfect, just opened PR: https://github.com/Flam3rboy/puppeteer-stream/pull/32
