### ISSUE TITLE
Using FFmpeg underneath the hood?

### ISSUE THREAD

**Issue by toshvelaga** [Flam3rboy/puppeteer-stream#31]
Hey great library! I am using it for a project as it seems to be the only one I could find that supports both video and audio. My question for you is how does the library work from a 10,000 ft overview. I am guessing it uses FFmpeg underneath the hood to capture the video and audio right? I am writing an article and wanted to mention this library as a good solution to quickly record. Thank you so much!

**Comment by Flam3rboy** [comment]
It works by making use of the tab recorder api of chrome which is accessible by this puppeteer-stream browser extension, which is loaded on launch.
When you want to record a webpage, puppeteer-stream notifies the extension to start recording (with the specified parameters). After that chrome starts capturing the audio and video of the page in a MediaStream, which is then converted into multiple packets using the MediaRecorder Api and transmitted back to puppeteer. You will then receive a webm stream that you can further process.
Puppeteer-stream doesn’t use ffmpeg under the hood, but the stream can be passed and [converted to ffmpeg](https://github.com/Flam3rboy/puppeteer-stream/blob/main/examples/ffmpeg.js) (if wanted).
Fun fact, you can even record DRM content using the tab recorder api.

**Comment by toshvelaga** [comment]
Ok awesome thank you so much for this! Will include this in the article.

**Comment by Flam3rboy** [comment]
I would love to read the article when you published it 😄

**Comment by toshvelaga** [comment]
Absolutely, just published it :):

https://medium.com/@toshvelaga/recording-webrtc-with-a-ghost-participant-using-puppeteer-104756e2be40

**Comment by krupeshanadkat-byjus** [comment]
Great to know its working, I had found that [chrome tabCapture](https://developer.chrome.com/docs/extensions/reference/tabCapture/) api can record audio & video both for the given tab.

I am stuck with drm videos in my use case, puppeteer-stream is not able to record that, it shows blank screen with no audio.

I know disabling chrome hardware acceleration seems to solve this issue, but that causes poor performance of my website.
