### ISSUE TITLE
livestreaming to twitch using ffmpeg

### ISSUE THREAD

**Issue by toshvelaga** [Flam3rboy/puppeteer-stream#39]
Hi there. I have a webRTC application that I am trying to add livestreaming to. I am trying to set up a small test where I can livestream to twitch using puppeteer-stream and ffmpeg. It seems as if I am only sending data to twitch right before the script ends. Do you know what I am doing wrong in the code below? Thank you! 

```js
const { launch, getStream } = require('puppeteer-stream')
const fs = require('fs')
const { exec } = require('child_process')

require('dotenv').config()

// puppeteer stream + FFmpeg example: https://github.com/Flam3rboy/puppeteer-stream/blob/main/examples/ffmpeg.js

const ffmpegConfig = (twitch) => {
  return `ffmpeg -i - -v error -c:v libx264 -preset veryfast -tune zerolatency -c:a aac -strict -2 -ar 44100 -b:a 64k -y -use_wallclock_as_timestamps 1 -async 1 -bufsize 1000 -f flv ${twitch}`
}

let twitch =
  'rtmp://dfw.contribute.live-video.net/app/' + process.env.TWITCH_STREAM_KEY

async function test() {
  const browser = await launch({
    executablePath:
      '/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',
    defaultViewport: {
      width: 1920,
      height: 1080,
    },
  })

  const page = await browser.newPage()
  await page.goto('https://www.youtube.com/watch?v=dQw4w9WgXcQ')
  const stream = await getStream(page, {
    audio: true,
    video: true,
    frameSize: 1000,
  })
  console.log('recording')
  // this will pipe the stream to ffmpeg and convert the webm to mp4 format
  const ffmpeg = exec(ffmpegConfig(twitch))

  ffmpeg.stderr.on('data', (chunk) => {
    console.log(chunk.toString())
  })

  stream.pipe(ffmpeg.stdin)

  setTimeout(async () => {
    await stream.destroy()
    stream.on('end', () => {
      console.log('stream has ended')
    })
    ffmpeg.stdin.setEncoding('utf8')
    ffmpeg.stdin.write('q')
    ffmpeg.stdin.end()
    ffmpeg.kill()

    console.log('finished')
  }, 1000 * 40)
}

test()
```
Right before the script ends loading indicator shows up
<img width="1259" alt="Screen Shot 2022-02-18 at 10 35 38 PM" src="https://user-images.githubusercontent.com/38474161/154788509-4de40f03-6255-4005-a8ba-9a2770952563.png">

<img width="790" alt="Screen Shot 2022-02-18 at 11 01 39 PM" src="https://user-images.githubusercontent.com/38474161/154788569-545f6f30-2709-4c55-b832-7c909826cd22.png">

**Comment by Flam3rboy** [comment]
Have you tried increasing the timeout just for testing?

**Comment by toshvelaga** [comment]
yeah I've tried increasing it to 80, similar result

**Comment by Flam3rboy** [comment]
Can you send the logs of your script?

**Comment by toshvelaga** [comment]
hmmmm, so I actually ran it again and it actually started working this time. Here's the code: https://github.com/toshvelaga/webrtc-video/blob/main/test.js it's all open source atm

**Comment by Flam3rboy** [comment]
I can't access it 😂

**Comment by Flam3rboy** [comment]
When I try it, I get this error:
```
[matroska,webm @ 0x7fc14100d800] File ended prematurely at pos. 2547673 (0x26dfd9)
```
So its seems like ffmpeg is having a problem with webm

**Comment by toshvelaga** [comment]
> I can't access it 😂

Sorry about that haha, this should work now: https://github.com/toshvelaga/webrtc-video/blob/main/test.js

**Comment by Flam3rboy** [comment]
It works when I change the ffmpeg config to:
```
return `ffmpeg -i - -v error -c:v libx264 -preset veryfast -tune zerolatency -c:a aac -f flv ${twitch}`;
```

**Comment by toshvelaga** [comment]
ok awesome, thanks so much! Both our configs seem to be working but yours seems to be producing more reliable results i think. If I can get this to work in production I'll right another blog post about it :). 
 
<img width="1224" alt="Screen Shot 2022-02-19 at 2 17 37 AM" src="https://user-images.githubusercontent.com/38474161/154794907-8367408a-08b3-4320-a120-bec7e2d46327.png">
