### ISSUE TITLE
Enable support for headless mode?

### ISSUE THREAD

**Issue by williamwesterlund** [Flam3rboy/puppeteer-stream#4]
As the title suggests, would it be possible to enable support for headless mode?

**Comment by Flam3rboy** [comment]
only possible, if puppeteer allows extensions in headless mode:
https://github.com/puppeteer/puppeteer/issues/659

Or if I fundamentally change the library to record the audio and video of a virtual window

**Comment by williamwesterlund** [comment]
Thank you for fast reply, keep up the good work!

**Comment by flashjames** [comment]
> only possible, if puppeteer allows extensions in headless mode:
> [puppeteer/puppeteer#659](https://github.com/puppeteer/puppeteer/issues/659)
> 
> Or if I fundamentally change the library to record the audio and video of a virtual window

"only possible, if puppeteer allows extensions in headless mode:"
So I may be wrong, but browserless.io has a solution without using an extension (or have I missed somewhere where they load an extension?)
https://docs.browserless.io/blog/2020/06/09/screencast.html

With code at: https://github.com/browserless/chrome/blob/master/src/apis/screencast.ts

But according to their api, it needs to start in headful: https://docs.browserless.io/docs/screencast

So I'm a bit confused.

**My question really is:**
If I'm correct, the code from browserless doesnt use an extension, but still needs headful.
Are there any more limitations in headless more than the "cant load extensions in headless", that makes the need for headful for screencasting?

**Comment by Flam3rboy** [comment]
The solution that browserless uses doesn't support audio and is using the chrome dev tools protocol that could be used in headless mode.
However I'm using the extension api to record the browser tab with video and **audio**.

**Comment by flashjames** [comment]
@Flam3rboy alright, thank you for that clarification

**Comment by darksupremo** [comment]
not sure if something changed, but now it shows that it support audio:
https://docs.browserless.io/docs/screencast

"Audio is now supported in our screencast API as of docker version 1.8.0."

**Comment by Flam3rboy** [comment]
oh interesting, I'll have a look

**Comment by Flam3rboy** [comment]
@darksupremo https://github.com/browserless/chrome/search?q=Audio
I don't find any code regarding Audio capture and how they did accomplish it

**Comment by Flam3rboy** [comment]
It seems like they also did my approach and used an extension with tabcapture xD
https://github.com/browserless/chrome/commit/f13a76ccd3d6391c5b97131ed172e4eb33e44711#diff-2671e4d55d68edf7506a2b7773f4f94e2294679a32e4f1719d490baf5dffa06eR13

**Comment by darksupremo** [comment]
it looks like a old commit, their old implementation was based on extension, but it looks that it's not the case anymore..

**Comment by Flam3rboy** [comment]
yeah you are right, but I don't find the audio part for the current implementation

**Comment by darksupremo** [comment]
Yeah, looks like that docs is outdated, it's still not supported :(

changelog:

v1.34.0:
screencast API no longer supports audio or the setPreferences function in order to offer a better video experience. In order to set the width/height, simply set a page width height to what you'd like.

...

1.8.0:
Video capture now supports audio and browser width/height.

**Comment by Livan-pro** [comment]
Found interesting comment in chromium issue about extension support in headless mode: https://bugs.chromium.org/p/chromium/issues/detail?id=706008#c36.
@Flam3rboy, could you take a look? Does it help?

**Comment by Flam3rboy** [comment]
@Livan-pro this looks promising, I'll try it later 👍

**Comment by ryanjt** [comment]
> @Livan-pro yes I can confirm that recording with this extension works, if I use the chrome browser as executable path and add the `args: ["--headless=chrome"],` option.

Can confirm this works by adding this to the launch options i.e
`browser = await launch({
        args: ['--headless=chrome']
	});`

**Comment by vyk12** [comment]
> @Livan-pro yes I can confirm that recording with this extension works, if I use the chrome browser as executable path and add the `args: ["--headless=chrome"],` option.

Hello and thanks a lot for your work 👍

I did exactly that, I am on Mac OS (Google Chrome 108.0.5359.124), I have set the executable path to `"/Applications/Google Chrome.app/Contents/MacOS/Google Chrome"` and launched the browser with `args: ['--headless=chrome']  `

However, when trying to stream the audio, an error is raised: `Error: Evaluation failed: ReferenceError: START_RECORDING is not defined`

How did you get your setup to work? Did you use a specific version of Chrome?

**Comment by ryanjt** [comment]
> > @Livan-pro yes I can confirm that recording with this extension works, if I use the chrome browser as executable path and add the `args: ["--headless=chrome"],` option.
> 
> Hello and thanks a lot for your work 👍
> 
> I did exactly that, I am on Mac OS (Google Chrome 108.0.5359.124), I have set the executable path to `"/Applications/Google Chrome.app/Contents/MacOS/Google Chrome"` and launched the browser with `args: ['--headless=chrome'] `
> 
> However, when trying to stream the audio, an error is raised: `Error: Evaluation failed: ReferenceError: START_RECORDING is not defined`
> 
> How did you get your setup to work? Did you use a specific version of Chrome?

Hey there,

It's been a good while since I have used this extension - so I'll try my best to help!

I did not encounter this error when I was using this extension. I didn't have a set version of Chrome installed either, maybe latest at the time? 

Another point to mention was that I was using Windows not Mac..

However from what I recall I was able to use headless mode as I was trying to use pupetteer to grab audio from a website and send that audio over Discord!

**Comment by vyk12** [comment]
> Hey there,
> 
> It's been a good while since I have used this extension - so I'll try my best to help!
> 
> I did not encounter this error when I was using this extension. I didn't have a set version of Chrome installed either, maybe latest at the time?
> 
> Another point to mention was that I was using Windows not Mac..
> 
> However from what I recall I was able to use headless mode as I was trying to use pupetteer to grab audio from a website and send that audio over Discord!

That was fast thanks!
My use case is pretty much the same, I am only interested into grabbing the audio of a webpage, but as a first step I'll just save it into a local file.
Maybe it is a Mac restriction, as you pointed out you were on Windows. I'll download a linux Docker image and test it.
Thanks for the tip!

**Comment by ryanjt** [comment]
> > Hey there,
> > It's been a good while since I have used this extension - so I'll try my best to help!
> > I did not encounter this error when I was using this extension. I didn't have a set version of Chrome installed either, maybe latest at the time?
> > Another point to mention was that I was using Windows not Mac..
> > However from what I recall I was able to use headless mode as I was trying to use pupetteer to grab audio from a website and send that audio over Discord!
> 
> That was fast thanks! My use case is pretty much the same, I am only interested into grabbing the audio of a webpage, but as a first step I'll just save it into a local file. Maybe it is a Mac restriction, as you pointed out you were on Windows. I'll download a linux Docker image and test it. Thanks for the tip!

I had a look at the old project I was using this for and I don't seem to be doing anything special; just simply setuping the the browser with the args:  `args: ['--headless=chrome']`. 

I did notice I have a viewport set here.. which doesn't make sense as it's "headless mode" but it must of been redundant code left in from when I was testing with headless disabled. I don't see any references to any specific versions of chrome so it must of just been using the latest version of chrome that was available on my PC at the time.

**Comment by darloski** [comment]
For those that this flag suddenly stopped working and capturing audio in the new version of Chrome (v109), the flag changed from '--headless=chrome' to '--headless=new'. Use this to run in a headless mode. You are welcome. :-)

**Comment by 21paradox** [comment]
https://developer.chrome.com/articles/new-headless/
quick tested in my pc , headeless mode works now.
```js
async function test() {
	const browser = await launch({
		defaultViewport: {
			width: 1920,
			height: 1080,
		},
	       args: [
			`--headless=new`,  // this will enable the new headless mode (chrome v109)
		]
	});
     ...
}
test();
```

**Comment by nivhsay** [comment]
On a debian docker container, no matter what size I give for `defaultViewport ` or  `--window-size`, I always end up with a recording of 800 x 600.

This could well be linked to  https://github.com/puppeteer/puppeteer/issues/10243

**Comment by nivhsay** [comment]
On linux, solution is [here](https://github.com/puppeteer/puppeteer/issues/10243#issuecomment-1584377903) if you are having trouble with window size in new headless.

**Comment by noeRls** [comment]
Hey I recommend mentioning it in the README.md, it's amazing that it works in headless!
