### ISSUE TITLE
multiple tabs

### ISSUE THREAD

**Issue by simllll** [Flam3rboy/puppeteer-stream#41]
Thanks for this amazing thing,
I'm using this quite heavily to stream our dashbaords to chromecasts :) I'm looking into performance optimizations right now, and tried to use one browser instance with multiple tabs instead of a single browser instance for each stream. Unfortunately this doesn't seem to work correctly, ffmpeg errors with weird errors like " Stream map '0:a' matches no streams." 

Is it possible to use this plugins with multiple tabs? If so, anything I'm missing here or could try to get it running?

Thanks
Simon

**Comment by simllll** [comment]
@Flam3rboy  anything I can do to get this issue solved? :) Any ideas what could be the issue?

**Comment by Flam3rboy** [comment]
I'll later look into it 👍

**Comment by TofanStefan** [comment]
@simllll Did you manage to record multiple browser instances at the same time?
I've made an endpoint for recording a page, if I call this endpoint 2 times, only the first call reproduces a valid webm file, the file for the second call is 0 kb

**Comment by simllll** [comment]
Yeah, the issue is quite easy to fix... Check out https://github.com/Flam3rboy/puppeteer-stream/pull/55

**Comment by TofanStefan** [comment]
@simllll Thanks alot! I've ran into a problem... It says "Property '_getTargetInfo' does not exist on type 'Target'".
I tried installing puppeteer 15 and I stii get the same error
