### ISSUE TITLE
Video its 00:00:00 long

### ISSUE THREAD

**Issue by SofiaFukushima** [Flam3rboy/puppeteer-stream#45]
Hello! I already have the stream recording but when this finish the video appears that it has 00.00.00 sec recorder. When i touch on the video i can see it but i can't go forward or anything, even i'm trying to compress but it says that the video doesn't have any time to compress.

**Comment by Flam3rboy** [comment]
yeah, thats sadly a problem with the chromium's tab recorder api, which I can't fix.

**Comment by SofiaFukushima** [comment]
Well I get a solution for this and to compress the video, with ffmpeg convert it into mp4, the space its the half that used to use, and the video have seconds now. 
I use:
ffmpeg -i videoPath/name.mkv -max_muxing_queue_size 1024 videoPath/name.mp4
Hope this would help other too.
