### ISSUE TITLE
stream doesn't work when "--use-fake-ui-for-media-stream" argument is passed

### ISSUE THREAD

**Issue by imbdb** [Flam3rboy/puppeteer-stream#52]
I need to record a page which needs access to webcam and mic. After passing `"--use-fake-ui-for-media-stream"`, stream is not working and recording results in a zero byte page.

example

```javascript
const file = fs.createWriteStream(__dirname + "/test.webm");

async function test() {
	const browser = await launch(puppeteer, {
		defaultViewport: {
			width: 1920,
			height: 1080,
		},
		args:[
			"--use-fake-ui-for-media-stream"
		]
	});

	const page = await browser.newPage();
	await page.goto("PAGE-THAT-NEEDS-MEDIA-PERMISSIONS");
	const stream = await getStream(page, { audio: true, video: true });
	console.log("recording");

	stream.pipe(file);
	setTimeout(async () => {
		await stream.destroy();
		file.close();
		console.log("finished");
	}, 1000 * 10);
}

test();
```

**Comment by imbdb** [comment]
Workaround 
We can use overridePermissions instead of the argument `--use-fake-ui-for-media-stream`

```javascript
const context = browser.defaultBrowserContext()
await context.overridePermissions("ORIGIN_OF_TEST_PAGE", ['camera', 'microphone'])
```

**Comment by zirismetov** [comment]
![image](https://user-images.githubusercontent.com/65970229/181461037-4349ba3d-eb0e-4135-83c8-5f98fa81bd7f.png)
![image](https://user-images.githubusercontent.com/65970229/181461117-d9288c74-b942-4c0e-b584-333b967201ff.png)
Any ideas how to fix that ?

**Comment by imbdb** [comment]
Closing Issue as I think the workaround is the way to go.

**Comment by Harsh4999** [comment]
You are saviour man
