### ISSUE TITLE
Unsupported mimeTypes can be removed from BrowserMimeType

### ISSUE THREAD

**Issue by DantrazTrev** [Flam3rboy/puppeteer-stream#61]
The current browser mime type type allow's values that are not supported by MediaRecorder API
https://github.com/Flam3rboy/puppeteer-stream/blob/c55492edc9fc6421e095cb173eff4cf8359431bf/src/PuppeteerStream.ts#L118-L129

A list for supported mimetypes can be drawn from the Chromium source code
https://source.chromium.org/chromium/chromium/src/+/main:third_party/blink/web_tests/fast/mediarecorder/MediaRecorder-isTypeSupported.html

**Comment by Flam3rboy** [comment]
done in 8109e4e
