### ISSUE TITLE
ProtocolError: Protocol error (Page.navigate): Target closed.

### ISSUE THREAD

**Issue by takisp08** [Flam3rboy/puppeteer-stream#65]
Hello, on puppeteer-stream on launch browser send error ProtocolError: Protocol error (Page.navigate): Target closed. But not only on one pc, I try to differents pc but  again  i have this error. This error only if launch with executable path. (eg Google Chrome)

**Comment by soklaymb** [comment]
@takisp08
I also faced the same issue when using the latest Chrome. However, when I switch to Chrome version 101.0.4951.64-1, it works normally.

```bash
# Install Chrome 101.0.4951.64-1 on Ubuntu (amd64)
$ sudo wget http://dl.google.com/linux/chrome/deb/pool/main/g/google-chrome-stable/google-chrome-stable_101.0.4951.64-1_amd64.deb
$ sudo dpkg -i google-chrome-stable_101.0.4951.64-1_amd64.deb
```

**Comment by takisp08** [comment]
Yes, I try this and now working. Thanks!!
